WebApp/Pages/AppIdentityUsers/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebApp.Data.Identity;
//using WebApp.Data.Models;

namespace WebApp.Pages.AppIdentityUsers
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly WebApp.Data.ApplicationDbContext _context;
        private readonly SignInManager<AppIdentityUser> _signInManager;

        public IndexModel(WebApp.Data.ApplicationDbContext context, SignInManager<AppIdentityUser> signInManager)
        {
            _signInManager = signInManager;
            _context = context;
        }


        public IList<AppIdentityUser> AppIdentityUser { get; set; } = default!;

        [BindProperty]
        public bool CheckedAll { get; set; }


        [BindProperty]
        public List<bool> IsChecked { get; set; }



        public async Task OnGetAsync()
        {
            if (_context.AppIdentityUser != null)
            {
                AppIdentityUser = await _context.AppIdentityUser.ToListAsync();
            }
        }

        public async Task<IActionResult> OnPostDeleteAsync()
        {
            var username = HttpContext.User.Identity.Name;
            var users = await _context.AppIdentityUser.ToListAsync();
            for (int i = 0; i < users.Count(); i++)
            {
                if (IsChecked[i])
                {
                    _context.AppIdentityUser.Remove(users[i]);
                    await _context.SaveChangesAsync();
                    if (users[i].UserName == username)
                    {
                        await Logout();
                    }
                }
            }
            return RedirectToPage("./Index");
        }

        
        public async Task<IActionResult> OnPostBlockAsync()
        {

            var username = HttpContext.User.Identity.Name;

            var users = await _context.AppIdentityUser.ToListAsync();
            for (int i = 0; i < users.Count(); i++)
            {
                if (IsChecked[i])
                {
                    users[i].LockoutEnabled = true;
                    users[i].LockoutEnd = DateTime.UtcNow.AddYears(100);
                    _context.Attach(users[i]).State = EntityState.Modified;

                    try
                    {
                        await _context.SaveChangesAsync();
                        if (users[i].UserName == username)
                        {
                            await Logout();
                        }

                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!UserExists(users[i].Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }

                }
            }
            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostUnblockAsync()
        {
            var users = await _context.AppIdentityUser.ToListAsync();
            for (int i = 0; i < users.Count(); i++)
            {
                if (IsChecked[i])
                {
                    users[i].LockoutEnabled = false;
                    users[i].LockoutEnd = DateTime.Now;
                    _context.Attach(users[i]).State = EntityState.Modified;

                    try
                    {
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!UserExists(users[i].Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }

                }
            }
            return RedirectToPage("./Index");
        }


        public async Task<IActionResult> Logout(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();

                // This needs to be a redirect so that the browser performs a new
                // request and the identity for the user gets updated.
            return RedirectToPage("./Identity/Account/Login");
        }


        private bool UserExists(string id)
        {
            return (_context.AppIdentityUser?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApp/Pages/AppIdentityUsers/Index.cshtml
@page
@model WebApp.Pages.AppIdentityUsers.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<form method="post">
<table class="table">
    <thead>
        <tr>
            <th>
        <!-- </snippet_Handlers> -->
            <div class="form-group">
                <input type="submit" asp-page-handler="Block" value="Block" class="btn btn-primary" />
            </div>

            </th>
            <th>
            <div class="form-group">
                <input type="submit" asp-page-handler="Unblock" value="Unblock" class="btn btn-primary" />
            </div>

            </th>
            <th>

            <div class="form-group">
                <input type="submit" asp-page-handler="Delete" value="Delete" class="btn btn-primary" />
            </div>

            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
</table>

<table class="table">

    <thead>
        <tr>
            <th>
                <input asp-for="CheckedAll" class="checkbox" /> 
                @if (Model.CheckedAll)
                    {
                        @for (int i = 0; i < Model.IsChecked.Count(); i++)
                        {
                            Model.IsChecked[i] = !Model.IsChecked[i];
                        }
                    }
                </th>
            <th>
                @Html.DisplayNameFor(model => model.AppIdentityUser[0].Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppIdentityUser[0].UserName)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.AppIdentityUser[0].Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AppIdentityUser[0].PhoneNumber)
            </th>
            <th>
                Blocked
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@for (var i = 0; i < Model.AppIdentityUser.Count();i++) {
        <tr>
            <td>
                <input asp-for="IsChecked[i]" class="checkbox" />
            </td>
            <td>
                @Model.AppIdentityUser[i].Id
            </td>
            <td>
                @Model.AppIdentityUser[i].UserName
            </td>
            <td>
                @Model.AppIdentityUser[i].Email
            </td>
            <td>
                @Model.AppIdentityUser[i].PhoneNumber
            </td>
            <td>
                @Model.AppIdentityUser[i].LockoutEnabled
            </td>
        </tr>
}
    </tbody>
</table>
        </form>