WebApp/Pages/Chat/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Data.Identity;
using WebApp.Data;

namespace WebApp.Pages.Chat
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly UserManager<AppIdentityUser> _userManager;
        private readonly ILogger<IndexModel> _logger;
        private readonly WebApp.Data.ApplicationDbContext _context;

        [BindProperty]
        public string MyUser { get; set; }

        [BindProperty]
        public List<SelectListItem> Users { get; set; }

        [BindProperty]
        public Message Message { get; set; } = default!;

        public IndexModel(ILogger<IndexModel> logger, UserManager<AppIdentityUser> userManager,
            WebApp.Data.ApplicationDbContext context)
        {
            _logger = logger;
            _userManager = userManager;
            _context = context;
        }



        public void OnGet()
        {
            Users = _userManager.Users.ToList()
                .Select(a => new SelectListItem { Text = a.UserName, Value = a.UserName })
                .OrderBy(s => s.Text).ToList();

            MyUser = User.Identity.Name;
        }

        

        public async Task<IActionResult> OnPostBaseAsync()
        {
            if (!ModelState.IsValid || _context.Messages == null || Message == null)
            {
                return Page();
            }

            _context.Messages.Add(Message);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }

    }
}

WebApp/Pages/Chat/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <form method="post">
     <div class="row">
         <div class="col-2">Receiver</div>
         <div class="col-4">@Html.DropDownList("receiver",Model.Users, "All")</div>
     </div>
     <div class="row">
         <div class="col-2">Message</div>
         <div class="col-4">
             <input asp-for="Message.Text"  type="text" id="message" /></div>
     </div>
     <div class="row">
         <div class="col-6">

             <input type="submit" asp-page-handler="Base" id="sendMessage" value="Send Message" />

         </div>
         </form>​
     </div>


     <div class="row">
         <div class="col-6">
             <ul id="messagesList"></ul>
         </div>
    </div>
</div>
​
@Html.Hidden("sender", Model.MyUser) <!--Current logged in username-->
​
@section Scripts
{
    <script src="~/microsoft-signalr/signalr.js"></script>
    <script src="~/js/chat.js" asp-append-version="true"></script>
}